---
title: "Parsing metadata from SOFT-formatted file (GEO)"
author: "Trang Tran"
date: "January 28, 2020"
output: html_notebook
---

```{r setup, include=FALSE, echo=FALSE}
library(magrittr)
library(ggplot2)
# Sys.setenv('DBDIR' = 'path/to/data/dir')
Sys.setenv('DBDIR' = './')
options(stringsAsFactors = FALSE)
knitr::opts_chunk$set(echo = TRUE)
softfile1 = file.path(Sys.getenv('DBDIR'), 'GSE71119_family.soft')
softfile2 = file.path(Sys.getenv('DBDIR'), 'GSE71120_family.soft')
source('../R/utils.R')
```

## Metadata for samples

```{r}
meta1 = read.soft2dataframe(softfile1, entryType = 'SAMPLE', idColumnName = 'SampleId')
meta2 = read.soft2dataframe(softfile2, entryType = 'SAMPLE', idColumnName = 'SampleId')

union(meta1$SampleId, meta2$SampleId)

sample.meta1 = meta1$Sample_characteristics_ch1 %>%
    lapply(function(x) {
        stringr::str_split(x, '\t') %>%
            sapply(function(y) { extract.keyvalue(y, separator = ': ') })
    }) %>%
    do.call(rbind, .) %>%
    data.frame() %>%
    cbind(meta1[,c('Sample_source_name_ch1', 'SampleId', 'Sample_title')])

sample.meta2 = meta2$Sample_characteristics_ch1 %>%
    lapply(function(x) {
        stringr::str_split(x, '\t') %>%
            sapply(function(y) { extract.keyvalue(y, separator = ': ') })
    }) %>%
    do.call(rbind, .) %>%
    data.frame() %>%
    cbind(meta2[,c('Sample_source_name_ch1', 'SampleId', 'Sample_title')])

sample.meta = rbind(sample.meta1, sample.meta2) %>%
    set_names(c('Metastasis', 'Time', 'PairedMicroarray', 'PairedMaterialSupport', 'MaterialSupport', 'FFPEQuality', 'CINSARC', 'SampleSourceName', 'SampleId', 'SampleName')) # standardize column names
```

```{r}
nrow(sample.meta)
length(unique(sample.meta$SampleId))
```

## Write (sequencing run) metadata files

```{r,eval=FALSE}
saveRDS(sample.meta, file = 'samples_metadata_geo.RDS')
```



